### ISSUE TITLE
Resource search page

### ISSUE THREAD

**Issue by eshiferax** [ECE-458-Resource-Manager/ResourceManager#6]
https://github.com/julianmontagna/filter-collections

**Comment by allankip** [comment]
Working on it

**Comment by allankip** [comment]
My most recent squashed commit adds a resource search page (at the /search route) with all of the search parameters and a list view of resources. What needs to be done next is connecting the search parameters to the filter-collections package to filter the resources list.

**Comment by eshiferax** [comment]
All my current progress is in the [search](https://github.com/ECE-458-Resource-Manager/ResourceManager/tree/search) branch - there are a couple things we need to fix before pull-requesting:
- I have put in a search-bar which should work on either tags or name (or both, or any other field/combination of fields we want to filter on), sorting and paging. These are all [filter-collections](https://atmospherejs.com/ericchen0121/filter-collections) functions and seem to be functional, but for some reason I can't get them to be reactive. By this I mean that if you type "Ama" into the search bar and select "submit", nothing happens, but if you then go to the resource-creation page and back to the homepage, the "Ama" name filter is applied. This holds true for the sorting (click on the column header for ascending/descending) and the pagination as well
- I actually pulled the filter-collections package from github and put it in the project because the [current version on atmosphere](https://atmospherejs.com/ericchen0121/filter-collections) isn't up-to-date and was having some issues
- I've stuffed all the HTML into search.html instead of the modular approach because I wasn't sure about how the filter-collections info was going to be passed, I can refactor it back into the old form once we have it functional and reactive

I used the package's [filter-collections-example](https://github.com/krishamoud/filter-collections-example) as a guideline when adding the forms, etc. ([live demo](http://filtercollections.meteor.com/))

**Comment by allankip** [comment]
- I forked the original filter-collections project, patched the non-reactivity issue, then added the fixed package to our project as a submodule
- The master branch is up to date with all of the changes
- Sorting by name works
- Searching by name works but I implemented it as a filter because the filter-collections sort methods are buggy (filter-collections search methods invoke filter methods under the hood anyway)
- 'required tags' and 'excluded tags' filters work individually but not together. This is because I couldn't find out how to set multiple filters on the same field
- All of the relevant filtering is done in the `runFilters()` method in search/tags_filter.js. `runFilters()` is called every time the search or tags parameters change
- I also added time span entry fields but they aren't hooked up to any backend code
